"""
flood_model.py - Couples terrain runoff, drainage network surcharge, and street ponding.
Computes water depth (cm) per street segment at 15-minute lead times (0 - 180 min).
Outputs GeoJSON files to outputs/depths_t{min}.geojson.
Can be executed as a standalone CLI script:
python model/flood_model.py --rain data/rainfall_event.csv
"""
import os
import sys
import json
import argparse
import pandas as pd
import numpy as np

# Ensure module path imports work whether run from root or model dir
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

from model.terrain import TerrainModel
from model.drainage import DrainageNetwork


def classify_depth(depth_cm: float) -> tuple:
    """
    Returns (level_name, color_hex, description) based on depth (cm):
    < 5 cm: Green (Passable)
    5 - 15 cm: Yellow (Slow traffic)
    15 - 30 cm: Orange (Small vehicles at risk)
    > 30 cm: Red (Avoid, impassable)
    """
    if depth_cm < 5.0:
        return "Green", "#10b981", "Passable"
    elif depth_cm <= 15.0:
        return "Yellow", "#f59e0b", "Slow traffic"
    elif depth_cm <= 30.0:
        return "Orange", "#f97316", "Small vehicles at risk"
    else:
        return "Red", "#ef4444", "Avoid, impassable"


class FloodModel:
    def __init__(self,
                 dem_path: str = None,
                 drains_path: str = None,
                 roads_path: str = None,
                 outputs_dir: str = None):
        base_dir = parent_dir
        self.dem_path = dem_path or os.path.join(base_dir, "data", "dem.tif")
        self.drains_path = drains_path or os.path.join(base_dir, "data", "drains.geojson")
        self.roads_path = roads_path or os.path.join(base_dir, "data", "roads.geojson")
        self.outputs_dir = outputs_dir or os.path.join(base_dir, "outputs")

        os.makedirs(self.outputs_dir, exist_ok=True)

        # Initialize sub-models
        self.terrain = TerrainModel(self.dem_path)
        self.drainage = DrainageNetwork(self.drains_path)
        self._load_roads()

    def _load_roads(self):
        with open(self.roads_path, "r", encoding="utf-8") as f:
            self.roads_geojson = json.load(f)

    def run_simulation(self, rain_csv_path: str) -> list:
        """
        Runs the simulation across all time steps in the rainfall CSV.
        Generates and saves GeoJSON depth layers for each time step.
        """
        if not os.path.exists(rain_csv_path):
            raise FileNotFoundError(f"Rainfall CSV not found at: {rain_csv_path}")

        df_rain = pd.read_csv(rain_csv_path)
        if "time_min" not in df_rain.columns or "intensity_mm_per_hr" not in df_rain.columns:
            raise ValueError("Rainfall CSV must have columns 'time_min' and 'intensity_mm_per_hr'")

        time_steps = df_rain.to_dict(orient="records")

        # Map drainage node positions for terrain runoff calculation
        node_coords = {nid: ndata["coords"] for nid, ndata in self.drainage.get_all_nodes().items()}

        # State tracking across time steps: accumulated ponding depth per drain node (cm)
        node_accumulated_depth = {nid: 0.0 for nid in node_coords}

        generated_files = []
        dt_hours = 15.0 / 60.0  # 15 minutes time step = 0.25 hours

        for step in time_steps:
            t = int(step["time_min"])
            rain_rate = float(step["intensity_mm_per_hr"])

            # 1. Surface runoff generated by terrain
            surface_inflows = self.terrain.get_node_catchment_runoff(node_coords, rain_rate)

            # 2. Hydraulic routing and surcharge detection in drain graph
            drain_results = self.drainage.route_flow(surface_inflows)
            node_surcharges = drain_results["node_surcharges"]

            # 3. Update ponding depth per drainage node
            for nid in node_coords:
                surcharge_rate = node_surcharges.get(nid, 0.0) # mm/hr
                ndata = self.drainage.nodes_data[nid]
                ponding_area = max(ndata["ponding_area_m2"], 500.0)

                # Surcharge inflow in mm/hr converts to water accumulation
                # 1 mm of water depth = 0.1 cm
                # Excess surcharge generates depth
                excess_mm_in_step = surcharge_rate * dt_hours
                new_depth_gain_cm = (excess_mm_in_step / 10.0) * (3000.0 / ponding_area)

                # Natural drain recovery / infiltration rate when surcharge ends: ~6-10 cm/hr (1.5-2.5 cm per 15 min)
                drain_rate_cm_step = 2.0 if surcharge_rate < 5.0 else 0.5
                curr_depth = node_accumulated_depth[nid] + new_depth_gain_cm
                curr_depth = max(0.0, curr_depth - drain_rate_cm_step)
                node_accumulated_depth[nid] = round(curr_depth, 2)

            # 4. Generate street depths GeoJSON
            features = []
            for feat in self.roads_geojson["features"]:
                props = dict(feat["properties"])
                geom = feat["geometry"]
                drain_node = props.get("drain_node")

                # Base depth from associated drain node
                raw_depth = node_accumulated_depth.get(drain_node, 0.0)

                # Micro-topographic depression amplification
                coords = geom["coordinates"]
                mid_idx = len(coords) // 2
                mid_lon, mid_lat = coords[mid_idx]
                elev = self.terrain.get_elevation_at(mid_lon, mid_lat)

                # Lower elevation roads pool deeper water
                elev_factor = max(0.6, 1.4 - (elev - 3.0) * 0.08)
                depth_cm = round(raw_depth * elev_factor, 1)

                level_name, color_hex, description = classify_depth(depth_cm)

                props["depth_cm"] = depth_cm
                props["level"] = level_name
                props["color"] = color_hex
                props["status"] = description
                props["time_min"] = t
                props["rain_intensity_mm_hr"] = rain_rate
                props["surcharged"] = depth_cm >= 5.0
                props["elevation_m"] = round(elev, 2)

                features.append({
                    "type": "Feature",
                    "id": props["id"],
                    "geometry": geom,
                    "properties": props
                })

            # Also add hotspot ponding points for surcharging nodes
            for snode in drain_results["surcharging_nodes"]:
                nid = snode["id"]
                node_depth = node_accumulated_depth.get(nid, 0.0)
                if node_depth >= 5.0:
                    level_name, color_hex, description = classify_depth(node_depth)
                    features.append({
                        "type": "Feature",
                        "id": f"HOTSPOT_{nid}",
                        "geometry": {
                            "type": "Point",
                            "coordinates": snode["coords"]
                        },
                        "properties": {
                            "id": f"HOTSPOT_{nid}",
                            "name": snode["name"],
                            "depth_cm": round(node_depth, 1),
                            "level": level_name,
                            "color": color_hex,
                            "status": description,
                            "time_min": t,
                            "surcharge_rate_mm_hr": snode["surcharge_rate_mm_hr"],
                            "is_hotspot": True
                        }
                    })

            output_file = os.path.join(self.outputs_dir, f"depths_t{t:03d}.geojson")
            out_geojson = {
                "type": "FeatureCollection",
                "metadata": {
                    "time_min": t,
                    "rain_intensity_mm_hr": rain_rate,
                    "max_depth_cm": max([f["properties"]["depth_cm"] for f in features] or [0.0])
                },
                "features": features
            }

            with open(output_file, "w", encoding="utf-8") as f:
                json.dump(out_geojson, f, indent=2)

            generated_files.append(output_file)

        print(f"Simulation complete: {len(generated_files)} forecast files generated in {self.outputs_dir}")
        return generated_files


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Urban Flood Nowcasting - Coupled Hydraulic Runoff Model")
    parser.add_argument("--rain", type=str, default=os.path.join(parent_dir, "data", "rainfall_event.csv"),
                        help="Path to rainfall event CSV (time_min, intensity_mm_per_hr)")
    parser.add_argument("--out", type=str, default=os.path.join(parent_dir, "outputs"),
                        help="Output directory for generated depth GeoJSON files")
    args = parser.parse_args()

    model = FloodModel(outputs_dir=args.out)
    model.run_simulation(args.rain)
